import type { KnowledgeGraphPayload } from "@/lib/canvasai-types";

export const MOCK_KNOWLEDGE_GRAPH: KnowledgeGraphPayload = {
  graph_id: "kg_mock_user_learning_map",
  user_id: "current-user",
  version: 4,
  generated_at: "2026-04-25T08:00:00.000Z",
  source_summary: {
    sessions: 10,
    documents: 3,
    cards: 21,
  },
  nodes: [
    {
      id: "linked-list-reversal",
      title: "Linked List Reversal",
      summary:
        "Reversal is a pointer-state transition: preserve next, redirect current.next, then advance previous and current.",
      revision_prompt:
        "Rehearse one node at a time. Before moving current, name which pointer would be lost if next was not saved.",
      mastery: 0.58,
      confidence: 0.81,
      cluster: "data-structures",
      tags: ["pointers", "mutation", "invariant"],
      evidence: ["canvas:reverse-linked-list", "recall:prediction-card"],
      source_session_ids: ["reverse-linked-list", "pointer-arith"],
      position: { x: 0, y: 0 },
    },
    {
      id: "pointer-aliasing",
      title: "Pointer Aliasing",
      summary:
        "Two names can reference the same memory location, so mutation through one path changes what the other path observes.",
      revision_prompt:
        "Draw two labels pointing at one box, mutate through either label, then explain why both labels see the change.",
      mastery: 0.46,
      confidence: 0.74,
      cluster: "memory-model",
      tags: ["memory", "references", "mutation"],
      evidence: ["canvas:pointer-arith", "document:pointer-notes"],
      source_session_ids: ["pointer-arith"],
      position: { x: -360, y: 110 },
    },
    {
      id: "loop-invariant",
      title: "Loop Invariants",
      summary:
        "An invariant is the condition that remains true before and after each iteration, even as local state changes.",
      revision_prompt:
        "State the invariant before the loop, after one iteration, and immediately before termination.",
      mastery: 0.64,
      confidence: 0.86,
      cluster: "algorithms",
      tags: ["proof", "iteration", "correctness"],
      evidence: ["canvas:bst-duplicates", "recall:invariant-card"],
      source_session_ids: ["demo", "reverse-linked-list"],
      position: { x: 360, y: 120 },
    },
    {
      id: "bst-ordering",
      title: "BST Ordering",
      summary:
        "Every subtree keeps the ordering relation: left values compare lower than root, right values compare higher than root.",
      revision_prompt:
        "Pick a subtree root and verify every incoming and outgoing edge against the ordering policy.",
      mastery: 0.72,
      confidence: 0.9,
      cluster: "data-structures",
      tags: ["trees", "ordering", "edge-cases"],
      evidence: ["canvas:demo", "document:clrs-bst"],
      source_session_ids: ["demo"],
      position: { x: 650, y: -120 },
    },
    {
      id: "stack-frames",
      title: "Stack Frames",
      summary:
        "A function call creates a frame for parameters, local values, return metadata, and the value copied back to the caller.",
      revision_prompt:
        "Trace a call and return. Identify what is copied, what is popped, and what still exists after return.",
      mastery: 0.52,
      confidence: 0.78,
      cluster: "systems",
      tags: ["calls", "memory", "lifetime"],
      evidence: ["canvas:stack-frames"],
      source_session_ids: ["stack-frames"],
      position: { x: -640, y: -150 },
    },
    {
      id: "react-flow-schema",
      title: "React Flow Schema",
      summary:
        "Canvas state is a strict graph payload: nodes hold position and display data, edges hold source, target, label, and animation state.",
      revision_prompt:
        "Convert one teaching step into JSON. Check that every edge source and target exists in nodes.",
      mastery: 0.67,
      confidence: 0.83,
      cluster: "frontend",
      tags: ["schema", "canvas", "validation"],
      evidence: ["document:react-flow-api", "agent:schema-enforcer"],
      source_session_ids: ["demo"],
      position: { x: 110, y: 330 },
    },
    {
      id: "spaced-repetition",
      title: "Spaced Repetition",
      summary:
        "Review scheduling should depend on performance and confidence so weak concepts return sooner than fluent ones.",
      revision_prompt:
        "Pick a low-mastery topic and create a question that forces retrieval without showing the answer first.",
      mastery: 0.61,
      confidence: 0.8,
      cluster: "algorithms",
      tags: ["recall", "scheduling", "metacognition"],
      evidence: ["active-recall:sessions"],
      source_session_ids: ["reverse-linked-list", "demo"],
      position: { x: -130, y: -300 },
    },
    {
      id: "loss-functions",
      title: "Loss Functions",
      summary:
        "A loss function turns model predictions into an error signal that optimization can minimize.",
      revision_prompt:
        "Compare mean squared error and cross-entropy by naming what each punishes most strongly.",
      mastery: 0.39,
      confidence: 0.69,
      cluster: "algorithms",
      tags: ["ml", "optimization", "error-signal"],
      evidence: ["canvas:gradient-descent-intro"],
      source_session_ids: ["gradient-descent-intro"],
      position: { x: 1020, y: 310 },
    },
    {
      id: "gradient-descent",
      title: "Gradient Descent",
      summary:
        "Gradient descent iteratively updates parameters in the direction that most reduces the current loss.",
      revision_prompt:
        "Draw one parameter update and explain why the sign of the gradient determines the direction.",
      mastery: 0.34,
      confidence: 0.64,
      cluster: "algorithms",
      tags: ["ml", "optimization", "derivatives"],
      evidence: ["canvas:gradient-descent-intro", "recall:loss-direction"],
      source_session_ids: ["gradient-descent-intro"],
      position: { x: 1260, y: 500 },
    },
    {
      id: "oauth-callbacks",
      title: "OAuth Callbacks",
      summary:
        "An auth callback exchanges a provider token or code for an application session and redirects back into the product.",
      revision_prompt:
        "Trace the callback path and identify which step proves user identity versus which step creates local session state.",
      mastery: 0.49,
      confidence: 0.73,
      cluster: "systems",
      tags: ["auth", "sessions", "redirects"],
      evidence: ["code:app/auth/callback/route.ts"],
      source_session_ids: ["auth-flow"],
      position: { x: -1040, y: 430 },
    },
  ],
  edges: [
    {
      id: "pointer-aliasing-linked-list-reversal",
      source: "pointer-aliasing",
      target: "linked-list-reversal",
      relation: "prerequisite",
      strength: 0.91,
      evidence: "Linked list reversal depends on tracking which pointer owns each reference before mutation.",
      source_session_ids: ["reverse-linked-list", "pointer-arith"],
    },
    {
      id: "loop-invariant-linked-list-reversal",
      source: "loop-invariant",
      target: "linked-list-reversal",
      relation: "extends",
      strength: 0.84,
      evidence: "The reversal loop preserves previous as the reversed prefix and current as the unreversed suffix.",
      source_session_ids: ["reverse-linked-list"],
    },
    {
      id: "loop-invariant-bst-ordering",
      source: "loop-invariant",
      target: "bst-ordering",
      relation: "analogous",
      strength: 0.72,
      evidence: "BST ordering and loop invariants both express constraints that must remain true across operations.",
      source_session_ids: ["demo"],
    },
    {
      id: "stack-frames-pointer-aliasing",
      source: "stack-frames",
      target: "pointer-aliasing",
      relation: "extends",
      strength: 0.68,
      evidence: "Call frames explain where pointer variables live while aliasing explains what memory they reference.",
      source_session_ids: ["stack-frames", "pointer-arith"],
    },
    {
      id: "react-flow-schema-linked-list-reversal",
      source: "react-flow-schema",
      target: "linked-list-reversal",
      relation: "debugs",
      strength: 0.62,
      evidence: "A valid canvas schema is needed to visualize each pointer edge transition.",
      source_session_ids: ["reverse-linked-list"],
    },
    {
      id: "spaced-repetition-loop-invariant",
      source: "spaced-repetition",
      target: "loop-invariant",
      relation: "debugs",
      strength: 0.57,
      evidence: "Low-confidence invariant cards should return sooner in review.",
      source_session_ids: ["demo", "reverse-linked-list"],
    },
    {
      id: "loss-functions-gradient-descent",
      source: "loss-functions",
      target: "gradient-descent",
      relation: "prerequisite",
      strength: 0.82,
      evidence: "Gradient descent needs a loss surface before a gradient direction is meaningful.",
      source_session_ids: ["gradient-descent-intro"],
    },
  ],
  update_plan: {
    trigger: "session_export",
    read_endpoint: "GET /knowledge-graph/current",
    write_endpoint: "POST /knowledge-graph/from-session/{session_id}",
    algorithm:
      "Extract topic candidates and relations from new session artifacts, merge against existing topics by canonical id and embedding similarity, then recompute graph communities and revision prompts.",
    notes: [
      "This mock payload should be replaced by the backend response once graph storage exists.",
      "Keep evidence ids so every topic and edge can be traced back to sessions, documents, or recall cards.",
      "Use LLMs for extraction/summarization, then use deterministic graph algorithms for merging, ranking, clustering, and layout.",
    ],
  },
};
